
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    API_WEATHER_KEY: 'b1209277c80f16637f10a77107c88145',
    API_WEATHER_URL: 'https://api.openweathermap.org/data/2.5',
  };
